// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInm8Zqpv2hAnZboN1SDsnnvMW1K86gzM',
    appId: '1:147549991561:web:bbc127e8b0c6ec464a0c58',
    messagingSenderId: '147549991561',
    projectId: 'medicalapp-dd743',
    authDomain: 'medicalapp-dd743.firebaseapp.com',
    storageBucket: 'medicalapp-dd743.appspot.com',
    measurementId: 'G-VF0M9DR2CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_H8rp63_JQxo4WyZFUQw-zBHzyoN43QA',
    appId: '1:147549991561:android:ab277e8b246fd9cd4a0c58',
    messagingSenderId: '147549991561',
    projectId: 'medicalapp-dd743',
    storageBucket: 'medicalapp-dd743.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEnwRqeYuBefkS3MbabBdLiGyO5Lf37s8',
    appId: '1:147549991561:ios:7b264b44106dedbe4a0c58',
    messagingSenderId: '147549991561',
    projectId: 'medicalapp-dd743',
    storageBucket: 'medicalapp-dd743.appspot.com',
    iosBundleId: 'com.example.medicalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDInm8Zqpv2hAnZboN1SDsnnvMW1K86gzM',
    appId: '1:147549991561:web:5b1b3d74fd770f254a0c58',
    messagingSenderId: '147549991561',
    projectId: 'medicalapp-dd743',
    authDomain: 'medicalapp-dd743.firebaseapp.com',
    storageBucket: 'medicalapp-dd743.appspot.com',
    measurementId: 'G-X50XXGFEKC',
  );
}
